// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See VTile.h for the primary calling header

#ifndef VERILATED_VTILE___024ROOT_H_
#define VERILATED_VTILE___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_threads.h"

class VTile__Syms;

class VTile___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        IData/*31:0*/ Tile__DOT__icache__DOT__addr_reg;
        CData/*0:0*/ Tile__DOT__icache__DOT__is_alloc;
        VlWide<4>/*127:0*/ Tile__DOT__icache__DOT__wdata;
        CData/*0:0*/ Tile__DOT__icache__DOT___wen_T_3;
        IData/*19:0*/ Tile__DOT__icache__DOT__wmask;
        CData/*0:0*/ Tile__DOT__icache__DOT__wen;
        CData/*0:0*/ Tile__DOT__icache__DOT__ren_reg;
        VlWide<4>/*127:0*/ Tile__DOT__icache__DOT__rdata;
        VlWide<4>/*127:0*/ Tile__DOT__icache__DOT__rdata_buf;
        VlWide<8>/*255:0*/ Tile__DOT__icache__DOT___d_T_2;
        VlWide<8>/*255:0*/ Tile__DOT__icache__DOT___d_T_4;
        VL_OUT(io_nasti_aw_bits_addr,31,0);
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__icache__DOT__dataMem_0_0;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__icache__DOT__dataMem_0_1;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__icache__DOT__dataMem_0_2;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__icache__DOT__dataMem_0_3;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__icache__DOT__dataMem_1_0;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__icache__DOT__dataMem_2_1;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__icache__DOT__dataMem_2_2;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__icache__DOT__dataMem_2_3;
        VlWide<8>/*255:0*/ Tile__DOT__dcache__DOT___d_T_2;
        VlWide<8>/*255:0*/ Tile__DOT__dcache__DOT___d_T_4;
        IData/*31:0*/ Tile__DOT__dcache__DOT__cpu_data;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__dcache__DOT__dataMem_1_1__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__dcache__DOT__dataMem_1_1__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__dcache__DOT__dataMem_1_1__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__dcache__DOT__dataMem_3_2__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__dcache__DOT__dataMem_3_2__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__dcache__DOT__dataMem_3_2__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__dcache__DOT__dataMem_2_0__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__dcache__DOT__dataMem_2_0__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__dcache__DOT__dataMem_2_0__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__dcache__DOT__dataMem_0_3__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__dcache__DOT__dataMem_0_3__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__dcache__DOT__dataMem_0_3__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__dcache__DOT__dataMem_0_2__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__dcache__DOT__dataMem_0_2__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__dcache__DOT__dataMem_0_2__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__dcache__DOT__dataMem_2_1__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__dcache__DOT__dataMem_2_1__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__dcache__DOT__dataMem_2_1__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__dcache__DOT__dataMem_0_1__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__dcache__DOT__dataMem_0_1__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__dcache__DOT__dataMem_0_1__v0;
        VlWide<8>/*255:0*/ Tile__DOT__dcache__DOT__d;
        IData/*19:0*/ Tile__DOT__dcache__DOT__metaMem_tag_rmeta_data;
        CData/*3:0*/ Tile__DOT__dcache__DOT__cpu_mask;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__dcache__DOT__dataMem_3_0__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__dcache__DOT__dataMem_3_0__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__dcache__DOT__dataMem_3_0__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__dcache__DOT__dataMem_1_2__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__dcache__DOT__dataMem_1_2__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__dcache__DOT__dataMem_1_2__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__dcache__DOT__dataMem_3_1__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__dcache__DOT__dataMem_3_1__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__dcache__DOT__dataMem_3_1__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__dcache__DOT__dataMem_1_3__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__dcache__DOT__dataMem_1_3__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__dcache__DOT__dataMem_1_3__v0;
        VL_IN8(io_nasti_aw_ready,0,0);
        VL_OUT8(io_nasti_aw_valid,0,0);
        VL_IN8(io_nasti_w_ready,0,0);
        VL_OUT8(io_nasti_w_valid,0,0);
        VL_OUT8(io_nasti_w_bits_last,0,0);
    };
    struct {
        VL_OUT8(io_nasti_b_ready,0,0);
        VL_IN8(io_nasti_b_valid,0,0);
        VL_IN8(io_nasti_ar_ready,0,0);
        VL_OUT8(io_nasti_ar_valid,0,0);
        VL_OUT8(io_nasti_r_ready,0,0);
        VL_IN8(io_nasti_r_bits_last,0,0);
        CData/*0:0*/ Tile__DOT__icache_io_nasti_ar_valid;
        CData/*0:0*/ Tile__DOT__dcache_io_nasti_w_valid;
        CData/*0:0*/ Tile__DOT__dcache_io_nasti_w_bits_last;
        CData/*0:0*/ Tile__DOT__dcache_io_nasti_b_ready;
        CData/*0:0*/ Tile__DOT__arb_io_icache_ar_ready;
        CData/*0:0*/ Tile__DOT__arb_io_dcache_w_ready;
        CData/*0:0*/ Tile__DOT__arb_io_nasti_aw_valid;
        CData/*0:0*/ Tile__DOT__arb_io_nasti_b_ready;
        CData/*0:0*/ Tile__DOT__arb_io_nasti_r_ready;
        CData/*0:0*/ Tile__DOT__icache__DOT__is_dirty;
        CData/*2:0*/ Tile__DOT__dcache__DOT___GEN_107;
        VL_OUT(io_nasti_ar_bits_addr,31,0);
        VlWide<4>/*127:0*/ Tile__DOT__dcache__DOT__read;
        VL_OUT64(io_nasti_w_bits_data,63,0);
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__dcache__DOT__dataMem_0_0;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__dcache__DOT__dataMem_1_0;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__dcache__DOT__dataMem_1_2;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__dcache__DOT__dataMem_1_3;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__dcache__DOT__dataMem_2_2;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__dcache__DOT__dataMem_2_3;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__dcache__DOT__dataMem_3_0;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__dcache__DOT__dataMem_3_1;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__dcache__DOT__dataMem_0_0__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__dcache__DOT__dataMem_0_0__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__dcache__DOT__dataMem_0_0__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__dcache__DOT__dataMem_2_2__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__dcache__DOT__dataMem_2_2__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__dcache__DOT__dataMem_2_2__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__dcache__DOT__dataMem_1_0__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__dcache__DOT__dataMem_1_0__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__dcache__DOT__dataMem_1_0__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__dcache__DOT__dataMem_2_3__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__dcache__DOT__dataMem_2_3__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__dcache__DOT__dataMem_2_3__v0;
        CData/*0:0*/ Tile__DOT__dcache_io_nasti_aw_valid;
        CData/*0:0*/ Tile__DOT__dcache_io_nasti_ar_valid;
        CData/*0:0*/ Tile__DOT__arb_io_dcache_aw_ready;
        CData/*0:0*/ Tile__DOT__arb_io_dcache_ar_ready;
        CData/*0:0*/ Tile__DOT__icache__DOT___wen_T;
        CData/*2:0*/ Tile__DOT__icache__DOT___GEN_107;
        CData/*2:0*/ Tile__DOT__icache__DOT___GEN_128;
        CData/*0:0*/ Tile__DOT__dcache__DOT___T_1;
        CData/*0:0*/ Tile__DOT__dcache__DOT__write_count;
        CData/*2:0*/ Tile__DOT__arb__DOT___GEN_0;
        CData/*2:0*/ Tile__DOT__arb__DOT___GEN_3;
        CData/*2:0*/ Tile__DOT__arb__DOT___GEN_8;
        QData/*63:0*/ Tile__DOT__dcache__DOT__refill_buf_1;
        VlWide<8>/*255:0*/ Tile__DOT__icache__DOT__d;
        QData/*63:0*/ Tile__DOT__dcache__DOT__refill_buf_0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__icache__DOT__dataMem_0_3__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__icache__DOT__dataMem_0_3__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__icache__DOT__dataMem_0_3__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__icache__DOT__dataMem_0_2__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__icache__DOT__dataMem_0_2__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__icache__DOT__dataMem_0_2__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__icache__DOT__dataMem_2_1__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__icache__DOT__dataMem_2_1__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__icache__DOT__dataMem_2_1__v0;
    };
    struct {
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__icache__DOT__dataMem_0_1__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__icache__DOT__dataMem_0_1__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__icache__DOT__dataMem_0_1__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__icache__DOT__dataMem_0_0__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__icache__DOT__dataMem_0_0__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__icache__DOT__dataMem_0_0__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__icache__DOT__dataMem_2_2__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__icache__DOT__dataMem_2_2__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__icache__DOT__dataMem_2_2__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__icache__DOT__dataMem_1_0__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__icache__DOT__dataMem_1_0__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__icache__DOT__dataMem_1_0__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__icache__DOT__dataMem_2_3__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__icache__DOT__dataMem_2_3__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__icache__DOT__dataMem_2_3__v0;
        VL_IN64(io_nasti_r_bits_data,63,0);
        QData/*63:0*/ Tile__DOT__icache__DOT__refill_buf_0;
        QData/*63:0*/ Tile__DOT__icache__DOT__refill_buf_1;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__icache__DOT__dataMem_1_1;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__icache__DOT__dataMem_1_2;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__icache__DOT__dataMem_1_3;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__icache__DOT__dataMem_3_0;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__icache__DOT__dataMem_3_1;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__icache__DOT__dataMem_3_3;
        VlWide<8>/*255:0*/ Tile__DOT__icache__DOT__v;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__icache__DOT__dataMem_1_1__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__icache__DOT__dataMem_1_1__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__icache__DOT__dataMem_1_1__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__icache__DOT__dataMem_3_0__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__icache__DOT__dataMem_3_0__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__icache__DOT__dataMem_3_0__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__icache__DOT__dataMem_1_2__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__icache__DOT__dataMem_1_2__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__icache__DOT__dataMem_1_2__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__icache__DOT__dataMem_3_1__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__icache__DOT__dataMem_3_1__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__icache__DOT__dataMem_3_1__v0;
        VlWide<8>/*255:0*/ Tile__DOT__icache__DOT___v_T_1;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__icache__DOT__dataMem_3_2__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__icache__DOT__dataMem_3_2__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__icache__DOT__dataMem_3_2__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__icache__DOT__dataMem_2_0__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__icache__DOT__dataMem_2_0__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__icache__DOT__dataMem_2_0__v0;
        CData/*0:0*/ Tile__DOT__icache_io_cpu_resp_valid;
        CData/*0:0*/ Tile__DOT__dcache_io_cpu_resp_valid;
        VlWide<8>/*255:0*/ Tile__DOT__dcache__DOT___hit_T;
        VL_IN8(io_host_fromhost_valid,0,0);
        VL_IN(io_host_fromhost_bits,31,0);
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___cycle_T_1;
        VlUnpacked<IData/*19:0*/, 256> Tile__DOT__icache__DOT__metaMem_tag;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__icache__DOT__dataMem_3_3__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__icache__DOT__dataMem_3_3__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__icache__DOT__dataMem_3_3__v0;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__icache__DOT__dataMem_1_3__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__icache__DOT__dataMem_1_3__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__icache__DOT__dataMem_1_3__v0;
        IData/*19:0*/ Tile__DOT__icache__DOT__metaMem_tag_rmeta_data;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_193;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__cycle;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__cycleh;
        CData/*0:0*/ Tile__DOT__dcache__DOT___T;
        CData/*0:0*/ Tile__DOT__dcache__DOT__read_count;
        CData/*0:0*/ __Vdly__Tile__DOT__dcache__DOT__read_count;
    };
    struct {
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__started;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___time_T_1;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_2;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_121;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_168;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_179;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_200;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__mbadaddr;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_169;
        IData/*31:0*/ Tile__DOT__dcache_io_cpu_resp_bits_data;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__lshift;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__dcache__DOT__dataMem_0_1;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__dcache__DOT__dataMem_0_2;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__dcache__DOT__dataMem_0_3;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__dcache__DOT__dataMem_1_1;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__dcache__DOT__dataMem_2_0;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__dcache__DOT__dataMem_2_1;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__dcache__DOT__dataMem_3_2;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__dcache__DOT__dataMem_3_3;
        VlWide<4>/*127:0*/ Tile__DOT__dcache__DOT__rdata_buf;
        CData/*0:0*/ Tile__DOT__dcache__DOT__wen;
        CData/*2:0*/ Tile__DOT__dcache__DOT__state;
        CData/*0:0*/ Tile__DOT__dcache__DOT__is_alloc_reg;
        CData/*0:0*/ Tile__DOT__dcache__DOT__hit;
        CData/*0:0*/ Tile__DOT__dcache__DOT__read_wrap_out;
        CData/*0:0*/ Tile__DOT__dcache__DOT___wen_T;
        CData/*0:0*/ Tile__DOT__dcache__DOT__is_dirty;
        CData/*7:0*/ Tile__DOT__dcache__DOT__metaMem_tag_rmeta_addr_pipe_0;
        CData/*0:0*/ Tile__DOT__dcache__DOT___ren_T_2;
        CData/*0:0*/ Tile__DOT__dcache__DOT__ren_reg;
        CData/*2:0*/ Tile__DOT__dcache__DOT___GEN_108;
        CData/*2:0*/ Tile__DOT__dcache__DOT___GEN_128;
        VlWide<4>/*127:0*/ Tile__DOT__dcache__DOT__rdata;
        CData/*7:0*/ __Vdlyvdim0__Tile__DOT__dcache__DOT__dataMem_3_3__v0;
        CData/*7:0*/ __Vdlyvval__Tile__DOT__dcache__DOT__dataMem_3_3__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__dcache__DOT__dataMem_3_3__v0;
        VlUnpacked<IData/*19:0*/, 256> Tile__DOT__dcache__DOT__metaMem_tag;
        CData/*2:0*/ __Vdly__Tile__DOT__dcache__DOT__state;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT___daddr_T;
        IData/*31:0*/ Tile__DOT__icache__DOT__cpu_data;
        VlWide<8>/*255:0*/ Tile__DOT__dcache__DOT__v;
        CData/*2:0*/ __Vdly__Tile__DOT__icache__DOT__state;
        VlWide<8>/*255:0*/ Tile__DOT__dcache__DOT___v_T_1;
        CData/*0:0*/ Tile__DOT__icache__DOT__read_wrap_out;
        CData/*2:0*/ Tile__DOT__arb__DOT__state;
        VL_IN8(io_nasti_r_valid,0,0);
        VlWide<8>/*255:0*/ Tile__DOT__icache__DOT___hit_T;
        CData/*0:0*/ Tile__DOT__icache__DOT__hit;
        CData/*2:0*/ Tile__DOT__icache__DOT__state;
        CData/*0:0*/ Tile__DOT__icache__DOT__is_alloc_reg;
        CData/*3:0*/ Tile__DOT__icache__DOT__cpu_mask;
        IData/*31:0*/ Tile__DOT__dcache__DOT__addr_reg;
        CData/*0:0*/ Tile__DOT__dcache__DOT__is_alloc;
        IData/*19:0*/ Tile__DOT__dcache__DOT__wmask;
        VlWide<4>/*127:0*/ Tile__DOT__dcache__DOT__wdata;
        CData/*0:0*/ Tile__DOT__dcache__DOT___wen_T_3;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath_io_dcache_req_valid;
        CData/*4:0*/ Tile__DOT__core__DOT__dpath__DOT___io_dcache_req_bits_mask_T_10;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__alu_io_sum;
        CData/*2:0*/ Tile__DOT__core__DOT__ctrl_io_imm_sel;
        SData/*11:0*/ Tile__DOT__core__DOT__dpath__DOT__immGen__DOT___io_out_T_5;
        CData/*1:0*/ Tile__DOT__core__DOT__dpath__DOT___io_dcache_req_bits_mask_T;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__fe_reg_pc;
        QData/*32:0*/ Tile__DOT__core__DOT__dpath__DOT__pc;
    };
    struct {
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__mepc;
        QData/*32:0*/ Tile__DOT__core__DOT__dpath__DOT___GEN_31;
        QData/*34:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_239;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__ew_reg_pc;
        CData/*2:0*/ Tile__DOT__core__DOT__ctrl_io_ld_type;
        CData/*1:0*/ Tile__DOT__core__DOT__ctrl_io_st_type;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__ew_reg_csr_in;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__pc_check;
        CData/*1:0*/ Tile__DOT__core__DOT__dpath__DOT__st_type;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__rs1;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__ew_reg_alu;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__wb_en;
        CData/*1:0*/ Tile__DOT__core__DOT__dpath__DOT__wb_sel;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__iaddrInvalid;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__laddrInvalid;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__saddrInvalid;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__isEcall;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__isEbreak;
        CData/*2:0*/ Tile__DOT__core__DOT__dpath__DOT__csr_cmd;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__illegal;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__privValid;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__csrValid;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_0;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__mfromhost;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__time_;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__instret;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__instreth;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr_io_out;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_4;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_96;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__MTIE;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__MSIE;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_182;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_183;
        CData/*7:0*/ Tile__DOT__icache__DOT__metaMem_tag_rmeta_addr_pipe_0;
        CData/*0:0*/ Tile__DOT__icache__DOT___ren_T_2;
        VlWide<4>/*127:0*/ Tile__DOT__icache__DOT__read;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__icache__DOT__dataMem_2_0;
        VlUnpacked<CData/*7:0*/, 256> Tile__DOT__icache__DOT__dataMem_3_2;
        CData/*0:0*/ Tile__DOT__icache__DOT___T;
        CData/*0:0*/ Tile__DOT__icache__DOT__read_count;
        CData/*0:0*/ __Vdly__Tile__DOT__icache__DOT__read_count;
        CData/*4:0*/ __Vdlyvdim0__Tile__DOT__core__DOT__dpath__DOT__regFile__DOT__regs__v0;
        CData/*0:0*/ __Vdlyvset__Tile__DOT__core__DOT__dpath__DOT__regFile__DOT__regs__v0;
        IData/*31:0*/ __Vdlyvval__Tile__DOT__core__DOT__dpath__DOT__regFile__DOT__regs__v0;
        CData/*2:0*/ Tile__DOT__core__DOT__dpath__DOT__ld_type;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__timeh;
        VL_IN8(clock,0,0);
        VL_IN8(reset,0,0);
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr_io_stall;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr_io_expt;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__isEret;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__wen;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__ew_reg_inst;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__wdata;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_3;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_135;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_184;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_166;
        CData/*0:0*/ Tile__DOT__core__DOT__ctrl__DOT___ctrlSignals_T_709;
        CData/*0:0*/ Tile__DOT__core__DOT__ctrl__DOT___ctrlSignals_T_609;
        CData/*1:0*/ Tile__DOT__core__DOT__ctrl__DOT___ctrlSignals_T_576;
        CData/*2:0*/ Tile__DOT__core__DOT__ctrl__DOT___ctrlSignals_T_672;
        CData/*1:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__PRV;
    };
    struct {
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__mcause;
        CData/*1:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__PRV1;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__mtohost;
        CData/*1:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_176;
        CData/*1:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_178;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_191;
        VL_OUT(io_host_tohost,31,0);
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_181;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__MSIP;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__IE;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__IE1;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__mscratch;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__mtimecmp;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_165;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT__MTIP;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_180;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_97;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__csr__DOT___GEN_1;
        VlUnpacked<IData/*31:0*/, 32> Tile__DOT__core__DOT__dpath__DOT__regFile__DOT__regs;
        QData/*32:0*/ Tile__DOT__core__DOT__dpath__DOT___next_pc_T_9;
        CData/*1:0*/ Tile__DOT__core__DOT__ctrl_io_pc_sel;
        CData/*3:0*/ Tile__DOT__core__DOT__ctrl_io_alu_op;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__alu_io_A;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__alu_io_B;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__immGen_io_out;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__alu__DOT___shiftl_T_38;
        QData/*32:0*/ Tile__DOT__core__DOT__dpath__DOT__alu__DOT___shiftr_T_5;
        CData/*0:0*/ Tile__DOT__core__DOT__ctrl_io_inst_kill;
        CData/*0:0*/ Tile__DOT__core__DOT__ctrl__DOT___ctrlSignals_T_185;
        CData/*0:0*/ Tile__DOT__core__DOT__ctrl__DOT___ctrlSignals_T_240;
        CData/*0:0*/ Tile__DOT__core__DOT__ctrl__DOT___ctrlSignals_T_425;
        QData/*32:0*/ Tile__DOT__core__DOT__dpath__DOT__next_pc;
        CData/*0:0*/ Tile__DOT__core__DOT__dpath__DOT__brCond_io_taken;
        IData/*20:0*/ Tile__DOT__core__DOT__dpath__DOT__immGen__DOT__Jimm;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__rs2;
        IData/*31:0*/ Tile__DOT__core__DOT__dpath__DOT__fe_reg_inst;
        VL_OUT8(io_nasti_aw_bits_id,4,0);
        VL_OUT8(io_nasti_aw_bits_len,7,0);
        VL_OUT8(io_nasti_aw_bits_size,2,0);
        VL_OUT8(io_nasti_aw_bits_burst,1,0);
        VL_OUT8(io_nasti_aw_bits_lock,0,0);
        VL_OUT8(io_nasti_aw_bits_cache,3,0);
        VL_OUT8(io_nasti_aw_bits_prot,2,0);
        VL_OUT8(io_nasti_aw_bits_qos,3,0);
        VL_OUT8(io_nasti_w_bits_strb,7,0);
        VL_IN8(io_nasti_b_bits_id,4,0);
        VL_IN8(io_nasti_b_bits_resp,1,0);
        VL_OUT8(io_nasti_ar_bits_id,4,0);
        VL_OUT8(io_nasti_ar_bits_len,7,0);
        VL_OUT8(io_nasti_ar_bits_size,2,0);
        VL_OUT8(io_nasti_ar_bits_burst,1,0);
        VL_OUT8(io_nasti_ar_bits_lock,0,0);
        VL_OUT8(io_nasti_ar_bits_cache,3,0);
        VL_OUT8(io_nasti_ar_bits_prot,2,0);
        VL_OUT8(io_nasti_ar_bits_qos,3,0);
        VL_IN8(io_nasti_r_bits_id,4,0);
        VL_IN8(io_nasti_r_bits_resp,1,0);
        CData/*0:0*/ __Vclklast__TOP__clock;
    };
    VlMTaskVertex __Vm_mtaskstate_21;
    VlMTaskVertex __Vm_mtaskstate_10;
    VlMTaskVertex __Vm_mtaskstate_5;
    VlMTaskVertex __Vm_mtaskstate_24;
    VlMTaskVertex __Vm_mtaskstate_28;
    VlMTaskVertex __Vm_mtaskstate_19;
    VlMTaskVertex __Vm_mtaskstate_34;
    VlMTaskVertex __Vm_mtaskstate_16;
    VlMTaskVertex __Vm_mtaskstate_23;
    VlMTaskVertex __Vm_mtaskstate_14;
    VlMTaskVertex __Vm_mtaskstate_29;
    VlMTaskVertex __Vm_mtaskstate_36;
    VlMTaskVertex __Vm_mtaskstate_37;
    VlMTaskVertex __Vm_mtaskstate_39;
    VlMTaskVertex __Vm_mtaskstate_25;
    VlMTaskVertex __Vm_mtaskstate_9;
    VlMTaskVertex __Vm_mtaskstate_17;
    VlMTaskVertex __Vm_mtaskstate_8;
    VlMTaskVertex __Vm_mtaskstate_2;
    VlMTaskVertex __Vm_mtaskstate_20;
    VlMTaskVertex __Vm_mtaskstate_38;
    VlMTaskVertex __Vm_mtaskstate_26;
    VlMTaskVertex __Vm_mtaskstate_11;
    VlMTaskVertex __Vm_mtaskstate_3;
    VlMTaskVertex __Vm_mtaskstate_15;
    VlMTaskVertex __Vm_mtaskstate_22;
    VlMTaskVertex __Vm_mtaskstate_27;
    VlMTaskVertex __Vm_mtaskstate_32;
    VlMTaskVertex __Vm_mtaskstate_18;
    VlMTaskVertex __Vm_mtaskstate_35;
    VlMTaskVertex __Vm_mtaskstate_final;

    // INTERNAL VARIABLES
    VTile__Syms* const vlSymsp;

    // CONSTRUCTORS
    VTile___024root(VTile__Syms* symsp, const char* name);
    ~VTile___024root();
    VL_UNCOPYABLE(VTile___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
} VL_ATTR_ALIGNED(VL_CACHE_LINE_BYTES);


#endif  // guard
